spring.application.name=ht_vlxd
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/vlxd_db?replicaSet=rs0}
spring.data.mongodb.auto-index-creation=false
spring.thymeleaf.cache=false
app.seed-demo=${SEED_DEMO:false}
gemini.api.key=${GEMINI_API_KEY:}
